import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import QuestionChatWrapper from "@/entities/question-chat/question-chat-wrapper";
import BottomTab from "@/features/bottom-tab/bottom-tab";
import Footer from "@/features/footer/footer";
import HeaderWrapper from "@/features/header/header-wrapper";
import ClientLayout from "@/shared/ui/client-layout/client-layout";
import type { Metadata } from "next";
import { Roboto, Roboto_Condensed, Unbounded } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const heroSlides = [
  {
    id: 1,
    image: "/banner.webp",
  },
  {
    id: 2,
    image: "/banner.webp",
  },
  {
    id: 3,
    image: "/banner.webp",
  },
  {
    id: 4,
    image: "/banner.webp",
  },
  {
    id: 5,
    image: "/banner.webp",
  },
];

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`
          ${roboto.variable}
          ${robotoCondensed.variable}
          ${unbounded.variable}
          antialiased
        `}
      >
        <NextIntlClientProvider locale={locale}>
          <ClientLayout>
            <HeaderWrapper />
            {children}
            <QuestionChatWrapper />
            <BottomTab />
            <Footer />
          </ClientLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
